// Generated by dojo-bindgen on Wed, 30 Oct 2024 17:53:29 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace depths_of_dread {
    // Model definition for `depths_of_dread::systems::actions::actions::Moved` model
    public class Moved : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("direction")]
        public Direction direction;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        