// Generated by dojo-bindgen on Wed, 30 Oct 2024 17:53:29 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `depths_of_dread::models::Direction` enum
public abstract record Direction() : Enum {
    public record None() : Direction;
    public record Left() : Direction;
    public record Right() : Direction;
    public record Up() : Direction;
    public record Down() : Direction;
}


namespace depths_of_dread {
    // Model definition for `depths_of_dread::models::GameFloor` model
    public class GameFloor : ModelInstance {
        [ModelField("game_id")]
        public uint game_id;

        [ModelField("size")]
        public Vec2 size;

        [ModelField("path")]
        public Direction[] path;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        