// Generated by dojo-bindgen on Wed, 30 Oct 2024 17:53:29 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `depths_of_dread::models::Obstacle` struct
[Serializable]
public struct Obstacle {
    public ObstacleType obstacle_type;
    public Vec2 position;
}

// Type definition for `depths_of_dread::models::Vec2` struct
[Serializable]
public struct Vec2 {
    public uint x;
    public uint y;
}

// Type definition for `depths_of_dread::models::ObstacleType` enum
public abstract record ObstacleType() : Enum {
    public record FloorTrap() : ObstacleType;
    public record RangeTrap() : ObstacleType;
    public record MeleeEnemy() : ObstacleType;
    public record NoTile() : ObstacleType;
    public record FireTrap() : ObstacleType;
    public record PoisonTrap() : ObstacleType;
}


namespace depths_of_dread {
    // Model definition for `depths_of_dread::models::GameObstacles` model
    public class GameObstacles : ModelInstance {
        [ModelField("game_id")]
        public uint game_id;

        [ModelField("instances")]
        public Obstacle[] instances;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        