// Generated by dojo-bindgen on Wed, 30 Oct 2024 17:53:29 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `depths_of_dread::models::PowerUp` enum
public abstract record PowerUp() : Enum {
    public record DoubleDash() : PowerUp;
    public record Shield() : PowerUp;
    public record Sword() : PowerUp;
    public record PeriferalVision() : PowerUp;
    public record Spotlight() : PowerUp;
    public record FireSpheres() : PowerUp;
    public record Magnet() : PowerUp;
    public record FireDefense() : PowerUp;
    public record PoisonDefense() : PowerUp;
}


namespace depths_of_dread {
    // Model definition for `depths_of_dread::models::PlayerPowerUps` model
    public class PlayerPowerUps : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("powers")]
        public PowerUp[] powers;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        